[PHP]
extension_dir="C:\Program Files\PHP\8.5.4\nts\x64\ext"
extension=php_pdo_mysql.dll
extension=php_pdo_sqlite.dll
extension=php_pgsql.dll
extension=php_sqlite3.dll
extension=php_fileinfo.dll
extension=php_mbstring.dll
extension=php_openssl.dll
extension=php_gd.dll
extension=php_curl.dll

[Date]
date.timezone=America/Sao_Paulo
