[PHP]  
extension_dir=C:\php-8.4\ext  
extension=pdo_mysql
extension=pdo_sqlite
extension=sqlite3
extension=mbstring
extension=fileinfo  
extension=openssl  
extension=gd  
extension=curl  
  
[Date]  
date.timezone=America/Sao_Paulo 
